### ISSUE TITLE
Success is always 0, all other results are empty all the time

### ISSUE THREAD

**Issue by kevindennehy** [worthmine/Captcha-reCAPTCHA-V3#2]
Is this module broken?

Using exact sample with my private v3 key and the script call from webpage. The script call populates the captcha but the validation appears to not be working? No error codes are thrown.

Success = 0 - Score = Error Codes = Action = Timestamp =

$result->{success}  always == 0
$result->{score}  null
$result->{error-codes} null
$result->{action} null
$result->{challenge_ts} null

my $rc_html = Google::reCAPTCHA::v3->new(
            {
                    -secret => $private_key_V3
            }
    );

 my $result = $rc_html->request(
            { 
                    -response => 'response_token',
                    -remoteip => $ip, # optional 
            }
    );

**Comment by worthmine** [comment]
If you use [Google::reCAPTCHA::v3](https://metacpan.org/pod/Google::reCAPTCHA::v3) module then you have to go [here](https://github.com/justingit/Google-reCAPTCHA-v3/issues) 

I didn't know that but there might be another implementation by another Author
