### ISSUE TITLE
Failed test 'succeed to catch 'invalid-input-secret''

### ISSUE THREAD

**Issue by eserte** [worthmine/Captcha-reCAPTCHA-V3#5]
The test suite started to fail:
```
#   Failed test 'succeed to catch 'invalid-input-secret''
#   at t/01_compatibility.t line 8.
#          got: 'invalid-input-response'
#     expected: 'invalid-input-secret'
# Looks like you failed 1 test of 1.
t/01_compatibility.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

According to http://matrix.cpantesters.org/?dist=Captcha-reCAPTCHA-V3%200.05;reports=1#sl=7,1 the last pass report was in July 2024.

**Comment by worthmine** [comment]
Thank you for reporting. I will check my code

**Comment by worthmine** [comment]
The failure seems depending on `LWP::Protocol::https`,
And it may be caused by recent update of openSSL(@3.4), so I made [an Issue to Net::SSLeay](https://github.com/radiator-software/p5-net-ssleay/issues/493).

**Comment by worthmine** [comment]
@eserte How does it work now?
It seems [tests pass](http://matrix.cpantesters.org/?dist=Captcha-reCAPTCHA-V3+0.06).

**Comment by eserte** [comment]
http://matrix.cpantesters.org/?dist=Captcha-reCAPTCHA-V3%200.06 looks very green. Thanks for the fix.
